name: Update Main Repository

on:
  push:
    paths:
      - 'path/to/submodulo/*' # Ruta del submódulo que quieres monitorear
jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Update submodule
      run: |
      
        cd path/to/submodule
        git pull origin main

        cd ../..
        git add path/to/submodulo
        git commit -m "Update submodule"
        git push origin main
