name: Update Main Repository

on:
  push:

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Update submodule
      run: |
      
        git submodule update --remote --rebase
        git add -A
        git commit -m "Update submodule"
        git push origin main
