name: Update Main Repository

on:
  push:
    branches:
      - main
jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Update submodule
      run: |

        git config --global user.email "jonathanpeinado8@gmail.com"
        git config --global user.name "Jhonatan Yair"
        git submodule update --remote --rebase
        git add -A
        git commit -m "Update submodule"
        git push origin main
