name: Update Main Repository

on:
  push:
    branches:
      - main
jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Update submodule
      run: |

        git config --global user.email "jonathanpeinado8@gmail.com"
        git config --global user.name "Jhonatan Yair"

        ls
        cd $GITHUB_WORKSPACE/submodule
        git pull origin main

        cd ../
        ls

        git add -A

        # Verificar si hay cambios en el repositorio principal antes de hacer el commit
        if [ -n "$(git status --porcelain)" ]; then
        git commit -m "Update submodule"
        git push origin main
        else
          echo "No hay cambios para confirmar en el repositorio principal."
        fi
